# Generated by Django 4.2.1 on 2023-05-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_unconfirmedpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unconfirmedpost',
            options={'verbose_name': 'Предложенный пост', 'verbose_name_plural': 'Предложенные посты'},
        ),
    ]
